### ISSUE TITLE
It seems to be not detecting secrets in the scan. it always passes

### ISSUE THREAD

**Issue by sgore-godaddy** [godaddy/tartufo-action#13]
I added the action as following in one of our repos:

```yaml
# Workflow to run tartufo scan for PR

name: Tartufo

on:
  push:
    branches:
    - '*'

jobs:
  tartufo-scan:
    name: Tartufo Scan
    # No need to self-hosted runner, since this is purely looking at the Git repo that's already pushed
    runs-on: [self-hosted, pep-ci]
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0

      - name: Perform Scan
        uses: godaddy/tartufo-action@7e34fe798485a138ba59ecf533f5a5dd790351bb # v3.2.0
        with:
          entropy-sensitivity: 100
```

To verify if it detects secrets correctly or not, I added the following line in the readme:

```
the password is 7e84fe798485a138ba59ecf533f5a5dd790351bb
```

while locally it reports a problem, on github the action runs to completion without showing any error.
